//===- ToyDialectBase.cpp - Toy IR Dialect registration in MLIR ------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file initialize the ToyDialect for the Toy IR
//
//===----------------------------------------------------------------------===//

#include "Dialect/ToyDialect/ToyDialectBase.h"

// To-do: Later, here you have to include the header "ToyOps.h"
// Because we need "ToyOps.cpp.inc" to register to the "ToyDialect::initialize()"


using namespace mlir;
using namespace mlir::toy;

/// This .cpp file for declaring ToyDialectBase class is autogenerated by
/// CMake function (in include/Dialect/ToyDialect/CMakeLists.txt) using the flag
/// "-gen-dialect-defs". Without this file, we cannot initialize the Dialect.
/// ToyDialectBase instance will be owned by the mlir::MLIRContext.




//===----------------------------------------------------------------------===//
// ToyDialect
//===----------------------------------------------------------------------===//

/// Dialect initialization. This is the point of registration of types
/// and operations for the dialect.
/// Now it is doing nothing, just sitting ducks.
void ToyDialect::initialize() {
    // To-do: Add autogenerated ToyOps declaration (i.e. ToyOps.cpp.inc)
}